apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: pod-spec-volume-pvc-ref
spec:
  summary: |
    Validate PodSpec volume mount PersistentVolumeClaim reference.
  target: |
    Shortcut("PodSpec")
  cache: |
    cache.pvcs = 
      helpers.newNameLookupDict(
        ApiVersion('v1')
            .Kind("PersistentVolumeClaim")
            .many()
      );
  rule: |
    for(const volume of config.spec?.volumes ?? [])
    {
      if (volume.persistentVolumeClaim)
      {
        checkPvcRef(volume.name, volume.persistentVolumeClaim);
      }
    }

    function checkPvcRef(volumeName, pvcRef)
    {
      const pvcItem = cache.pvcs.resolve(pvcRef.claimName);
      if (!pvcItem)
      {
        error(`Could not find PersistentVolumeClaim ${pvcRef.claimName} referenced in volume ${volumeName}.`);
      }
    }