apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: istio-gateway-host-check
spec:
  target: |
    ApiVersion('networking.istio.io/v1beta1')
      .Kind('VirtualService')
  rule: |
    for(let gatewayName of (config.spec?.gateways || []))
    {
      let gateway = 
            ApiVersion('networking.istio.io/v1beta1')
              .Kind('Gateway')
              .name(gatewayName)
              .single();
        
      if (!gateway)
      {
        error(`Did not find Gateway ${gatewayName}`); 
      }
      else
      {
        for(const gatewayServer of (gateway.config.spec?.servers || []))
        {
          for(const host of gatewayServer.hosts || [])
          {
            if (host == "*") {
              error("Wildcard hosts are not allowed!");
            }
          }
        }
      }
    }