version: "1.0"

stages:
  - "clone"
  - "test"

steps:

  init:
    title: Init
    stage: clone
    image: codefresh/cli
    shell: bash
    commands:
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)
      - export PRODUCT_NAME=${{CF_REPO_NAME}}
      - cf_export PRODUCT_NAME=${PRODUCT_NAME}
      - cf_export MAIN_REPO_PATH=/codefresh/volume/repo.git
      - export DEMOS_REPO_NAME=demos
      - cf_export DEMOS_REPO_NAME=${DEMOS_REPO_NAME}
      - cf_export DEMOS_REPO_PATH=/codefresh/volume/${DEMOS_REPO_NAME}.git
      - 'echo "Repo: ${{CF_REPO_NAME}}"'
      - 'echo "Branch: ${{CF_BRANCH}}"'
      - 'echo "Revision: ${{CF_REVISION}}"'
      - 'echo "Author: ${{CF_COMMIT_AUTHOR}}"'
      - 'echo "Message: ${{CF_COMMIT_MESSAGE}}"'
      
  clone:
    title: Clone Repo
    stage: clone
    image: 'alpine/git:latest'
    working_directory: "/codefresh/volume"
    commands:
      - pwd
      - ls -la
      - rm -rf ${{MAIN_REPO_PATH}}
      - 'git clone https://${{CF_REPO_OWNER}}:${{GITHUB_TOKEN}}@github.com/${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}.git ${{MAIN_REPO_PATH}}'
      - ls -la
      - cd ${{MAIN_REPO_PATH}}
      - git reset --hard ${{CF_REVISION}}
      - ls -la

  clone_demos:
    title: Clone Demos Repo
    stage: clone
    image: 'alpine/git:latest'
    working_directory: "/codefresh/volume"
    commands:
      - pwd
      - ls -la
      - rm -rf ${{DEMOS_REPO_PATH}}
      - 'git clone https://${{CF_REPO_OWNER}}:${{GITHUB_TOKEN}}@github.com/${{CF_REPO_OWNER}}/${{DEMOS_REPO_NAME}}.git ${{DEMOS_REPO_PATH}}'
      - ls -la
      - cd ${{DEMOS_REPO_PATH}}
      - ls -la      

  validate:
    title: Run Tests
    stage: test
    image: 'kubevious/cli:latest'
    working_directory: ${{DEMOS_REPO_PATH}}
    commands:
      - kubevious --version