version: "1.0"

stages:
  - "clone"
  - "prepare"
  - "test"

steps:

  init:
    title: Init
    stage: clone
    image: codefresh/cli
    shell: bash
    commands:
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)
      - export PRODUCT_NAME=${{CF_REPO_NAME}}
      - cf_export PRODUCT_NAME=${PRODUCT_NAME}
      - cf_export MAIN_REPO_PATH=/codefresh/volume/repo.git
      - export DEMOS_REPO_NAME=demos
      - cf_export DEMOS_REPO_NAME=${DEMOS_REPO_NAME}
      - cf_export DEMOS_REPO_PATH=/codefresh/volume/${DEMOS_REPO_NAME}.git
      - cf_export SAMPLES_PATH=/codefresh/volume/samples
      - 'echo "Repo: ${{CF_REPO_NAME}}"'
      - 'echo "Branch: ${{CF_BRANCH}}"'
      - 'echo "Revision: ${{CF_REVISION}}"'
      - 'echo "Author: ${{CF_COMMIT_AUTHOR}}"'
      - 'echo "Message: ${{CF_COMMIT_MESSAGE}}"'
      
  clone:
    title: Clone Repo
    stage: clone
    image: 'alpine/git:latest'
    working_directory: "/codefresh/volume"
    commands:
      - pwd
      - ls -la
      - rm -rf ${{MAIN_REPO_PATH}}
      - 'git clone https://${{CF_REPO_OWNER}}:${{GITHUB_TOKEN}}@github.com/${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}.git ${{MAIN_REPO_PATH}}'
      - ls -la
      - cd ${{MAIN_REPO_PATH}}
      - git reset --hard ${{CF_REVISION}}
      - ls -la

  clone_demos:
    title: Clone Demos Repo
    stage: clone
    image: 'alpine/git:latest'
    working_directory: "/codefresh/volume"
    commands:
      - pwd
      - ls -la
      - rm -rf ${{DEMOS_REPO_PATH}}
      - 'git clone https://${{CF_REPO_OWNER}}:${{GITHUB_TOKEN}}@github.com/${{CF_REPO_OWNER}}/${{DEMOS_REPO_NAME}}.git ${{DEMOS_REPO_PATH}}'
      - ls -la
      - cd ${{DEMOS_REPO_PATH}}
      - ls -la

  prepare_charts:
    title: Prepare Charts
    stage: prepare
    image: kubevious/cicd_deployer:latest
    working_directory: ${{SAMPLES_PATH}}
    commands:
      - helm version
      - helm repo add traefik https://traefik.github.io/charts
      - helm template traefik/traefik --include-crds > traefik.yaml
     
  validate_hipster:
    title: Validate Hipster
    stage: test
    image: 'kubevious/cli:latest'
    working_directory: ${{DEMOS_REPO_PATH}}
    commands:
      - kubevious --version
      - kubevious guard --skip-community-rules ${{MAIN_REPO_PATH}}/index.yaml ${{DEMOS_REPO_PATH}}/guard/01-hipster-shop/hipster-chart/templates/
      - kubevious guard --skip-community-rules ${{MAIN_REPO_PATH}}/index.yaml ${{DEMOS_REPO_PATH}}/guard/01-hipster-shop/hipster-chart/templates/ ${{DEMOS_REPO_PATH}}/guard/01-hipster-shop/network-policies-chart/templates/
      - kubevious guard --skip-community-rules ${{MAIN_REPO_PATH}}/index.yaml ${{DEMOS_REPO_PATH}}/guard/01-hipster-shop/hipster-chart/templates/ ${{DEMOS_REPO_PATH}}/guard/01-hipster-shop/istio-chart/templates/ https://raw.githubusercontent.com/istio/istio/master/manifests/charts/base/crds/crd-all.gen.yaml

  validate_voter:
    title: Validate Voter
    stage: test
    image: 'kubevious/cli:latest'
    working_directory: ${{DEMOS_REPO_PATH}}
    commands:
      - kubevious --version
      - kubevious guard --skip-community-rules ${{MAIN_REPO_PATH}}/index.yaml ${{DEMOS_REPO_PATH}}/guard/02-voter-app/voter-chart/templates/

  validate_traefik:
    title: Validate Traefik
    stage: test
    image: 'kubevious/cli:latest'
    working_directory: ${{DEMOS_REPO_PATH}}
    commands:
      - kubevious --version
      - kubevious guard --skip-community-rules ${{MAIN_REPO_PATH}}/index.yaml ${{SAMPLES_PATH}}/traefik.yaml
      