apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: virtual-service-to-gateway-ref
spec:
  summary: |
    Validate Istio VirtualService to IstioGateway reference.
  target: |
    Api('networking.istio.io')
      .Kind('VirtualService')
  rule: |
    for(let gatewayName of (config.spec?.gateways || []))
    {
      let gateway = 
            Api('networking.istio.io')
              .Kind('Gateway')
              .name(gatewayName)
              .single();
        
      if (!gateway)
      {
        error(`Did not find Gateway ${gatewayName}`); 
      }
    }