apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: service-selector-ref
spec:
  summary: |
    Validate Service to PodSpec label selector reference.
  target: |
    ApiVersion('v1')
      .Kind('Service')
  cache: |
    cache.apps = helpers.newLabelLookupDict();
    for(const app of Shortcut("PodSpec")
                       .many())
    {
      cache.apps.add(app, app.config.metadata?.labels);
    }
  rule: |
    if (!config.spec.selector) {
      return;
    }

    if (!cache.apps.matchesSelector(config.spec.selector))
    {
      error("Could not find Applications for Service");
    }