apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: certificate-to-issuer-ref
spec:
  summary: |
    Validate CertManager Certificate to Issuer reference.
  target: |
    ApiVersion('cert-manager.io/v1')
      .Kind('Certificate')
  rule: |
    const issuer = ApiVersion('cert-manager.io/v1')
                    .Kind(config.spec?.issuerRef?.kind)
                    .name(config.spec?.issuerRef?.name)
                    .allNamespaces()
                    .single();
    if (!issuer) {
      error('Could not find the Certificate Issuer ${config.spec?.issuerRef?.kind}/${config.spec?.issuerRef?.name}');
    }