on: [push]

jobs:
  kubevious_validation:
    runs-on: ubuntu-latest
    name: Validation Run
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Demos
        uses: actions/checkout@v3
        with:
          repository: kubevious/demos
          path: demos.git
      - name: Checkout KubeFlow
        uses: actions/checkout@v3
        with:
          repository: kubeflow/pipelines
          path: kubeflow-pipelines.git
      - name: Checkout Carvel-YTT
        uses: actions/checkout@v3
        with:
          repository: vmware-tanzu/carvel-ytt
          path: carvel-ytt.git

      - name: Validation of Prometheus
        id: prometheus-validation
        uses: kubevious/cli@main
        with:
          helm_repo_url: https://prometheus-community.github.io/helm-charts
          helm_repo_name: prometheus-community
          helm_chart: prometheus
          helm_namespace: prometheus
          helm_include_crds: true
      - name: Validation of Traefik
        id: traefik-validation
        uses: kubevious/cli@main
        with:
          helm_repo_url: https://traefik.github.io/charts
          helm_repo_name: traefik
          helm_chart: traefik
          helm_namespace: traefik
          helm_include_crds: true
      - name: Validation of KubeFlow
        id: kubeflow-validation
        uses: kubevious/cli@main
        with:
          manifests: kubeflow-pipelines.git/manifests/kustomize/cluster-scoped-resources kubeflow-pipelines.git/manifests/kustomize/env/platform-agnostic
          mocks: demos.git/mocks/kubeflow/webhook-server-tls.yaml

      - name: Run Carvel-YTT
        id: carvel-ytt-template
        uses: vmware-tanzu/carvel-setup-action@v1
      - run: |
          ytt -f carvel-ytt.git/examples/playground/getting-started/example-hello-world/config.yml > ytt-example.yaml
      - name: Validate Carvel-YTT
        id: carvel-ytt-validation
        uses: kubevious/cli@main
        with:
          manifests: ytt-example.yaml